version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRES_MINUTES=${ACCESS_TOKEN_EXPIRES_MINUTES}
      - ACCESS_TOKEN_EXPIRES_DAYS=${ACCESS_TOKEN_EXPIRES_DAYS}

  frontend:
    build: ./auth-app-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
